CREATE DATABASE SportHub
GO
USE SportHub
GO
CREATE TABLE UserCredentials(
Id UNIQUEIDENTIFIER PRIMARY KEY,
Username NVARCHAR(40),
Email NVARCHAR(140),
Password NVARCHAR(50),
Role NVARCHAR(10),
IsOnline BIT
);

CREATE TABLE UserInfo(
Id INT IDENTITY(100,1),
UserId UNIQUEIDENTIFIER,
FirstName NVARCHAR(40),
LastName NVARCHAR(40),
DateOfBirth DATE,
SportLevel NVARCHAR(20),
Height INT,
Weight INT,
AboutMe NVARCHAR(150),
Motivation NVARCHAR(70),
AvatarUrl VARCHAR,
FOREIGN KEY (UserId) REFERENCES UserCredentials(Id)
ON DELETE CASCADE
);

CREATE TABLE Post(
Id INT IDENTITY(10,1) PRIMARY KEY,
Text NVARCHAR(MAX),
ImageUrl VARCHAR,
DateCreated DATE,
IsUpdated BIT,
IsAdmin BIT
);

CREATE TABLE UserPost(
UserId UNIQUEIDENTIFIER,
PostId INT,
FOREIGN KEY (UserId) REFERENCES UserCredentials(Id)
ON DELETE CASCADE,
FOREIGN KEY (PostId) REFERENCES Post(Id)
ON DELETE CASCADE
);

CREATE TABLE Comment(
Id INT IDENTITY(1,1) PRIMARY KEY,
UserId UNIQUEIDENTIFIER,
Text NVARCHAR(500),
DateCreated DATE,
IsUpdated BIT,
FOREIGN KEY (UserId) REFERENCES UserCredentials(Id)
);

CREATE TABLE PostComment(
CommentId INT,
PostId INT,
FOREIGN KEY (CommentId) REFERENCES Comment(Id)
ON DELETE CASCADE,
FOREIGN KEY (PostId) REFERENCES Post(Id)
ON DELETE CASCADE
);

CREATE TABLE UsersLike(
UserId UNIQUEIDENTIFIER,
PostId INT,
FOREIGN KEY (UserId) REFERENCES UserCredentials(Id)
ON DELETE CASCADE,
FOREIGN KEY (PostId) REFERENCES Post(Id)
ON DELETE CASCADE
);

CREATE TABLE Subscribes(
Id INT,
UserId UNIQUEIDENTIFIER,
SubscriberId UNIQUEIDENTIFIER,
FOREIGN KEY (UserId) REFERENCES UserCredentials(Id)
ON DELETE CASCADE,
FOREIGN KEY (SubscriberId) REFERENCES UserCredentials(Id)
);

CREATE TABLE SavedPost(
UserId UNIQUEIDENTIFIER,
PostId INT,
FOREIGN KEY (UserId) REFERENCES UserCredentials(Id)
ON DELETE CASCADE,
FOREIGN KEY (PostId) REFERENCES Post(Id)
ON DELETE CASCADE
);